title: "Oliver Lie"
description: "Game Developer"
theme: null
markdown: kramdown
permalink: pretty

sections:
  - id: projects
    name: Projects
  - id: career
    name: Career
  - id: skills
    name: Skills
  - id: research
    name: Research
